<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="optimization" nsURI="http://tools/descartes/librede/rrde/optimization"
    nsPrefix="tools.descartes.librede.rrde.optimization">
  <eClassifiers xsi:type="ecore:EClass" name="OptimizationConfiguration">
    <eStructuralFeatures xsi:type="ecore:EReference" name="containsOf" upperBound="-1"
        eType="#//RunCall" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IAlgorithm" abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="ConfigurationSettings" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="timeOut" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"
        defaultValueLiteral="-1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HillClimbingSettings" eSuperTypes="#//ConfigurationSettings">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="minimum" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        defaultValueLiteral="0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maximum" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        defaultValueLiteral="200"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tolerance" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        defaultValueLiteral="0.05"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maximumNumberOfSteps" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="startValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        defaultValueLiteral="60"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="stepSize" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        defaultValueLiteral="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RunCall">
    <eStructuralFeatures xsi:type="ecore:EReference" name="executes" lowerBound="1"
        eType="#//IAlgorithm"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="executesOn" lowerBound="1"
        upperBound="-1" eType="#//InputData"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="specifiedBy" lowerBound="1"
        eType="#//ConfigurationSettings"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InputData">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="location" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
