<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="optimization" nsURI="http://tools/descartes/librede/rrde/optimization"
    nsPrefix="librede-optimization">
  <eClassifiers xsi:type="ecore:EClass" name="OptimizationConfiguration">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A configuration of algorithms optimizing LibReDE configurations of estimation approaches."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="containsOf" upperBound="-1"
        eType="#//RunCall" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IConfigurationOptimizationAlgorithmSpecifier"
      abstract="true" interface="true">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="This is a basic interface for configurations of algorithms optimizing LibReDE configurations of estimation approaches."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="timeOut" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong" defaultValueLiteral="-1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="algorithmName" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LocalSearchSpecifier" eSuperTypes="#//IConfigurationOptimizationAlgorithmSpecifier">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tolerance" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble" defaultValueLiteral="0.05"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maximumNumberOfSteps" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong" defaultValueLiteral="-1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="stepSize" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble" defaultValueLiteral="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RunCall">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="One iteration of optimization specified by input or training data, a set of OptimizationSettings, an EstimationSpecification to optimize and one instance of an IConfigurationOptimizationAlgorithmSpecifier"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="algorithm" lowerBound="1"
        eType="#//IConfigurationOptimizationAlgorithmSpecifier" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="trainingData" lowerBound="1"
        upperBound="-1" eType="#//InputData" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="settings" lowerBound="1"
        eType="#//OptimizationSettings" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="estimationSpecification"
        lowerBound="1" eType="ecore:EClass ../../tools.descartes.librede.model/model/librede.ecore#//EstimationSpecification"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InputData">
    <eStructuralFeatures xsi:type="ecore:EReference" name="inputSpecification" lowerBound="1"
        eType="ecore:EClass ../../tools.descartes.librede.model/model/librede.ecore#//InputSpecification"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="description" lowerBound="1"
        eType="ecore:EClass ../../tools.descartes.librede.model/model/librede.ecore#//WorkloadDescription"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rootFolder" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OptimizationSettings">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A settings file containing several general parameters configuring the executing algorithm."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="validator" lowerBound="1"
        eType="ecore:EClass ../../tools.descartes.librede.model/model/librede.ecore#//ValidationSpecification"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parametersToOptimize" upperBound="-1"
        eType="#//IOptimizableParameter" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IterativeParameterOptimizerSpecifier"
      eSuperTypes="#//IConfigurationOptimizationAlgorithmSpecifier">
    <eOperations name="stop" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Boolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numberOfSplits" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Int" defaultValueLiteral="10"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numberOfExplorations" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Int" defaultValueLiteral="50"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IOptimizableParameter" abstract="true"
      interface="true">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="An interface for the different parameter types that can be optimized."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lowerBound" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Double"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="upperBound" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Double"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="startValue" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Double"
        iD="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GenericParameter" eSuperTypes="#//IOptimizableParameter">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StepSize" eSuperTypes="#//IOptimizableParameter"/>
  <eClassifiers xsi:type="ecore:EClass" name="WindowSize" eSuperTypes="#//IOptimizableParameter"/>
  <eClassifiers xsi:type="ecore:EClass" name="DataExportSpecifier" eSuperTypes="#//IConfigurationOptimizationAlgorithmSpecifier">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="OutputDirectory" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String" defaultValueLiteral="&quot;&quot;"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="multidimensional" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Boolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="splitConfigurations" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Boolean"
        defaultValueLiteral="false"/>
  </eClassifiers>
</ecore:EPackage>
